export const BRAINFUCK_EXEC_COMPLETE = "BRAINFUCK_EXEC_COMPLETE"
export const BRAINFUCK_EXEC_INCOMPLETE = "BRAINFUCK_EXEC_INCOMPLETE"
export const BRAINFUCK_EXEC_IO_PAUSE = "BRAINFUCK_EXEC_IO_PAUSE"
export const BRAINFUCK_EXEC_ERR = "BRAINFUCK_EXEC_ERR"

export const ABC_EXEC_COMPLETE = "ABC_EXEC_COMPLETE"
export const DEADSIMPLE_EXEC_COMPLETE = "DEADSIMPLE_EXEC_COMPLETE"
export const DEADSIMPLE_EXEC_ERR = "DEADSIMPLE_EXEC_ERR"